name: afronika
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

  smooth_page_indicator: ^1.1.0

  shared_preferences: ^2.5.3
  provider: ^6.1.5
  font_awesome_flutter: ^10.8.0
  flutter_secure_storage: ^9.0.0
  url_launcher: ^6.3.2
  app_links: ^6.4.0
  webview_flutter: ^4.13.0
  flutter_inappwebview: ^6.1.5
  webview_flutter_android: ^4.8.2
  webview_flutter_wkwebview: ^3.22.1
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  flutter_custom_tabs: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/roboto/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700

# ADD THIS SECTION HERE (after the flutter section)
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
flutter_native_splash:
  color: "#ffffff"  # Background color (white)
  image: assets/images/applogo.png  # Your app logo

  # Optional: Dark mode support
  color_dark: "#ffffff"  # Keep white background for dark mode too
  image_dark: assets/images/applogo.png

  # Android 12+ support
  android_12:
    image: assets/images/applogo.png
    color: "#ffffff"  # White background for Android 12+