name: afronika
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.2.0
  get: ^4.6.6
  smooth_page_indicator: ^1.1.0
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  firebase_database: ^11.3.9
  shared_preferences: ^2.5.3
  provider: ^6.1.5
  font_awesome_flutter: ^10.8.0
  flutter_secure_storage: ^9.0.0
  url_launcher: ^6.3.2
  app_links: ^6.4.0
  webview_flutter: ^4.13.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/roboto/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
